### ISSUE TITLE
Consideration of case in resource property names

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/indicia-docs-rest-api#2]
At the moment, the specification has adopted CamelCase with leading caps for many resource property names in an attempt to match to the field names defined for the NBN exchange format. However, this "feels" wrong for our system required properties like the id and href for a resource which are almost never represented with a single leading caps. So we've ended up with (for example) the following specification for a project resource's properties:
- id
- href
- Title
- Description

Similarly an observation resource has the following fields (this is just a few of those defined):
- id
- href
- DatasetName
- TaxonVersionKey

Shall we adopt camelCase without the leading caps? So we get:
- id
- href
- datasetName
- taxonVersionKey

That means our attribute names deviate from the NBN format a bit but it can be easily explained.

**Comment by japonicus** [comment]
I agree with you that the consistency among attributes would be good and that as 'Href' etc. would look odd I'd prefer camelCase for all attributes.

**Comment by dave-turvey** [comment]
I think we should adopt the camelCase without the leading caps as its a bit of a mixed bag at the moment.

**Comment by johnvanbreda** [comment]
Agreed. I'll do that...

**Comment by johnvanbreda** [comment]
Fixed
