### ISSUE TITLE
Warehouse1 IIS configuration

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/indicia-docs-rest-api#3]
For every 201 status code response with Location header we get some extra HTML embedded so our responses are invalid. It looks something like this:
```
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="http://...">here</a></body><?xml version="1.0" encoding="utf-8" standalone="yes”?>
{}
```
We would like to only get the JSON and no HTML added, so in the previous example it would only be: `{ }`

Is there something you could do about this? Here is more info online: https://stackoverflow.com/questions/12074730/w7-pro-iis-7-5-overwrites-php-location-header

**Comment by BirenRathod** [comment]
@kazlauskis 
I have implemented the setting of PHP. See if that make difference in response you get.

**Comment by kazlauskis** [comment]
No, it is still the same response.

**Comment by BirenRathod** [comment]
@kazlauskis 
Is there way I could test myself?

**Comment by kazlauskis** [comment]
Yes, you can use this, I will send you the token separately: 
```
curl --location --request POST 'https://devwarehouse.indicia.org.uk/index.php/services/rest/samples' \
--header 'Authorization: Bearer  JWT_TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
	"values": {
		"survey_id": 1,
		"entered_sref": "51.1, 1.2",
		"entered_sref_system": 4326,
		"date": "03/08/2020",
		"comment": "A sample comment test",
		"smpAttr:1": "Sunny"
	}
}'
```

**Comment by BirenRathod** [comment]
Thanks. that should be helpful.

**Comment by BirenRathod** [comment]
@kazlauskis 
It has now resolved.

**Comment by kazlauskis** [comment]
Thanks, which server is it? I have tried the dev warehouse and still got: 
```
<head>
	<title>Document Moved</title>
</head>

<body>
	<h1>Object Moved</h1>This document may be found <a
		HREF="https://devwarehouse.indicia.org.uk/index.php/services/rest/samples/9302789">here</a>
</body>
{"values":{"id":"9302789","created_on":"2020-09-09T14:46:14+01:00","updated_on":"2020-09-09T14:46:14+01:00"},"href":"https:\/\/devwarehouse.indicia.org.uk\/index.php\/services\/rest\/samples\/9302789"}
```

**Comment by BirenRathod** [comment]
@kazlauskis 
I'm afraid I tried every possible ways to solve this but I can't able to resolve this. I have tried the solution from your above referenced link but that has not worked too. I can only suggest at present by tweaking the code might give some positive result but that is very small window of opportunity.  

I found some PHP tricks to create REST-API -> https://www.allphptricks.com/create-and-consume-simple-rest-api-in-php/

**Comment by kazlauskis** [comment]
Yes, we have the API done and working, only the IIS is turning our responses into rubbish. This should really be solved at the server side but for the time being I can tackle this at the client-level. For other developers this would be a bigger issue though. Can the server be moved to Apache or something else?

**Comment by BirenRathod** [comment]
@kazlauskis Unfortunately not. We have to stick it with IIS. There may be solution of this some where it just we are not aware of it.
